### ISSUE TITLE
There is an uncaught "write after end" error somewhere

### ISSUE THREAD

**Issue by jancurn** [apifytech/proxy-chain#27]
```
Error: write after end
    at write_ (_http_outgoing.js:622:15)
    at ServerResponse.write (_http_outgoing.js:617:10)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at ServerResponse.<anonymous> (_stream_readable.js:707:7)
    at emitNone (events.js:106:13)
    at ServerResponse.emit (events.js:208:7)
    at Socket.ondrain (internal/http.js:20:44)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at onwriteDrain (_stream_writable.js:474:12)
    at afterWrite (_stream_writable.js:462:5)
    at onwrite (_stream_writable.js:455:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:876:12)
```

**Comment by jancurn** [comment]
Now it's happening even more

**Comment by jancurn** [comment]
Fixed in the latest release.
