### ISSUE TITLE
HTTP forwarder should only forward valid HTTP status codes

### ISSUE THREAD

**Issue by jancurn** [apifytech/proxy-chain#35]
Otherwise the proxy can crash with this error:

```
RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:194:11)
    at HandlerForward.onTrgResponse (/home/bob/proxy/node_modules/proxy-chain/build/handler_forward.js:158:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by jancurn** [comment]
Should be fixed in the new release
