### ISSUE TITLE
TypeError: Cannot read property 'pipe' of null

### ISSUE THREAD

**Issue by apienx** [apifytech/proxy-chain#57]
Null _trgSocket_ breaks Apify Actor run (see attached log for more details). 

```
2020-02-04T14:32:40.741Z /home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:110
2020-02-04T14:32:40.743Z             this.trgSocket.pipe(this.srcSocket);
2020-02-04T14:32:40.745Z                            ^
2020-02-04T14:32:40.747Z 
2020-02-04T14:32:40.749Z TypeError: Cannot read property 'pipe' of null
2020-02-04T14:32:40.751Z     at HandlerTunnelChain.onTrgRequestConnect (/home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:110:28)
2020-02-04T14:32:40.753Z     at Object.onceWrapper (events.js:313:26)
2020-02-04T14:32:40.755Z     at ClientRequest.emit (events.js:223:5)
2020-02-04T14:32:40.758Z     at Socket.socketOnData (_http_client.js:490:11)
2020-02-04T14:32:40.760Z     at Socket.emit (events.js:223:5)
2020-02-04T14:32:40.762Z     at addChunk (_stream_readable.js:309:12)
2020-02-04T14:32:40.764Z     at readableAddChunk (_stream_readable.js:290:11)
2020-02-04T14:32:40.766Z     at Socket.Readable.push (_stream_readable.js:224:10)
2020-02-04T14:32:40.768Z     at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

On Apify platform, Node.js v12.14.1, NPM version 6.13.4.

**Comment by jancurn** [comment]
Apparently, the `apify` package was using an old version of `proxy-chain` package, which might have caused this issue. Fixing this in https://github.com/apifytech/apify-js/commit/9cf05dc8d60a6892cfab9430006cf79a63d96f3e

Closing this now, please re-open the issue if it appears again with the new version.
