### ISSUE TITLE
Fix unhandled exception in HandlerTunnelChain.onTrgRequestConnect()

### ISSUE THREAD

**Issue by jancurn** [apifytech/proxy-chain#63]
```
Mar 07 16:38:50 ip-172-31-62-12 proxy@prod.log TypeError: Cannot read property '_httpMessage' of null
    at ServerResponse.detachSocket (_http_server.js:223:17)
    at HandlerTunnelChain.onTrgRequestConnect (/home/apifier/proxy/node_modules/proxy-chain/build/handler_tunnel_chain.js:91:30)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketOnData (_http_client.js:510:11)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by jancurn** [comment]
Fixed in https://github.com/apifytech/proxy-chain/commit/3fbc675271ec37d2c9321bf1e5a03c4790059ce3
