### ISSUE TITLE
Cannot read property pipe of null at HandlerTunnelChain.onTrgRequestConnect

### ISSUE THREAD

**Issue by mnmkng** [apifytech/proxy-chain#64]
Version: 4.3

```
2020-03-10T04:44:10.266Z /home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:111
2020-03-10T04:44:10.276Z             this.trgSocket.pipe(this.srcSocket);
2020-03-10T04:44:10.278Z                            ^
2020-03-10T04:44:10.279Z 
2020-03-10T04:44:10.281Z TypeError: Cannot read property 'pipe' of null
2020-03-10T04:44:10.283Z     at HandlerTunnelChain.onTrgRequestConnect (/home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:111:28)
2020-03-10T04:44:10.285Z     at Object.onceWrapper (events.js:418:26)
2020-03-10T04:44:10.287Z     at ClientRequest.emit (events.js:311:20)
2020-03-10T04:44:10.289Z     at Socket.socketOnData (_http_client.js:510:11)
2020-03-10T04:44:10.291Z     at Socket.emit (events.js:311:20)
2020-03-10T04:44:10.293Z     at addChunk (_stream_readable.js:294:12)
2020-03-10T04:44:10.294Z     at readableAddChunk (_stream_readable.js:275:11)
2020-03-10T04:44:10.296Z     at Socket.Readable.push (_stream_readable.js:209:10)
2020-03-10T04:44:10.298Z     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by jancurn** [comment]
Hopefully, fixed in https://github.com/apifytech/proxy-chain/commit/22b23315542463c2da60d60397c1ee712a86fe47

**Comment by AndreyBykov** [comment]
Version: 4.4 The error is still there, unfortunately:

```
2020-03-25T05:55:08.344Z /home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:117
2020-03-25T05:55:08.346Z             this.trgSocket.pipe(this.srcSocket);
2020-03-25T05:55:08.347Z                            ^
2020-03-25T05:55:08.348Z 
2020-03-25T05:55:08.350Z TypeError: Cannot read property 'pipe' of null
2020-03-25T05:55:08.351Z     at HandlerTunnelChain.onTrgRequestConnect (/home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:117:28)
2020-03-25T05:55:08.352Z     at ClientRequest.emit (events.js:311:20)
2020-03-25T05:55:08.354Z     at Socket.socketOnData (_http_client.js:510:11)
2020-03-25T05:55:08.355Z     at Socket.emit (events.js:311:20)
2020-03-25T05:55:08.356Z     at addChunk (_stream_readable.js:294:12)
2020-03-25T05:55:08.357Z     at readableAddChunk (_stream_readable.js:275:11)
2020-03-25T05:55:08.359Z     at Socket.Readable.push (_stream_readable.js:209:10)
2020-03-25T05:55:08.360Z     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by jancurn** [comment]
Here's another one from the system:

```
Apr 12 08:59:49 ip-172-31-92-253 proxy@prod.log TypeError: Cannot read property 'pipe' of null
    at HandlerTunnelChain.onTrgRequestConnect (/home/apifier/proxy/node_modules/proxy-chain/build/handler_tunnel_chain.js:117:28)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketOnData (_http_client.js:510:11)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by mnmkng** [comment]
Yet another one from a client:

```
2020-04-23T12:07:26.716Z ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://wallethub.com/r/?id=13309942i","retryCount":1,"id":"G90WaEgddXB1E0P"}
2020-04-23T12:07:26.870Z   Error: net::ERR_SSL_PROTOCOL_ERROR at https://wallethub.com/r/?id=13309942i
2020-04-23T12:07:26.872Z     at navigate (/home/myuser/node_modules/puppeteer/lib/FrameManager.js:120:37)
2020-04-23T12:07:26.874Z     at runMicrotasks (<anonymous>)
2020-04-23T12:07:26.877Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-04-23T12:07:26.878Z     at async FrameManager.navigateFrame (/home/myuser/node_modules/puppeteer/lib/FrameManager.js:94:17)
2020-04-23T12:07:26.880Z     at async Frame.goto (/home/myuser/node_modules/puppeteer/lib/FrameManager.js:406:12)
2020-04-23T12:07:26.882Z     at async Page.goto (/home/myuser/node_modules/puppeteer/lib/Page.js:672:12)
2020-04-23T12:07:26.885Z     at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/puppeteer_crawler.js:306:24)
2020-04-23T12:07:26.887Z     at async /home/myuser/node_modules/apify/build/utils.js:405:20
2020-04-23T12:07:26.889Z   -- ASYNC --
2020-04-23T12:07:26.891Z     at Frame.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:111:15)
2020-04-23T12:07:26.977Z     at Page.goto (/home/myuser/node_modules/puppeteer/lib/Page.js:672:49)
2020-04-23T12:07:26.979Z     at Page.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:112:23)
2020-04-23T12:07:26.982Z     at PuppeteerCrawler.gotoFunction (/home/myuser/src/main.js:124:29)
2020-04-23T12:07:26.984Z     at runMicrotasks (<anonymous>)
2020-04-23T12:07:26.986Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-04-23T12:07:26.988Z     at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/puppeteer_crawler.js:306:24)
2020-04-23T12:07:26.991Z     at async /home/myuser/node_modules/apify/build/utils.js:405:20
2020-04-23T12:07:28.402Z /home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:110
2020-04-23T12:07:28.407Z             this.trgSocket.pipe(this.srcSocket);
2020-04-23T12:07:28.408Z                            ^
2020-04-23T12:07:28.408Z 
2020-04-23T12:07:28.408Z TypeError: Cannot read property 'pipe' of null
2020-04-23T12:07:28.409Z     at HandlerTunnelChain.onTrgRequestConnect (/home/myuser/node_modules/proxy-chain/build/handler_tunnel_chain.js:110:28)
2020-04-23T12:07:28.409Z     at Object.onceWrapper (events.js:417:26)
2020-04-23T12:07:28.410Z     at ClientRequest.emit (events.js:310:20)
2020-04-23T12:07:28.410Z     at Socket.socketOnData (_http_client.js:510:11)
2020-04-23T12:07:28.410Z     at Socket.emit (events.js:310:20)
2020-04-23T12:07:28.420Z     at addChunk (_stream_readable.js:286:12)
2020-04-23T12:07:28.422Z     at readableAddChunk (_stream_readable.js:268:9)
2020-04-23T12:07:28.423Z     at Socket.Readable.push (_stream_readable.js:209:10)
2020-04-23T12:07:28.423Z     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by jancurn** [comment]
Hopefully this will fix it: https://github.com/apifytech/proxy-chain/pull/68
